name: Project 2 Autograder

on:
  push:
    paths:
      - "project-2/**"
      - ".github/workflows/project2-tests.yml"
      - "requirements.txt"
  pull_request:
    paths:
      - "project-2/**"
      - "requirements.txt"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project-2/requirements.txt

      - name: Run pytest
        run: pytest -q project-2/assignment/tests/test_project2.py
